language: elixir
elixir:
  - 1.5.1
otp_release:
  - 20.0
script:
  - mix test
  - mix credo --strict
  - MIX_ENV=docs mix inch --pedantic
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
env:
  - MIX_ENV=test
